stages:
  - build
  - tests

variables:
  REPOSITORY_URL: $REPOSITORY_URL
  GIT_SUBMODULE_STRATEGY: recursive
  DEBUG: "false"
  CI: "true"
  DOCKER_HOST: tcp://localhost:2375/
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""

build:
  stage: build
  extends:
    - .only-defaults
  script:
    - make build-tests
    - docker push $REPOSITORY_URL/deps-ci/deps_lil_chyn:$CI_PIPELINE_ID

ci:
  stage: tests
  extends:
    - .only-defaults
  coverage: '/\d+\%\s*$/'
  script:
    - docker pull $REPOSITORY_URL/deps-ci/deps_lil_chyn:$CI_PIPELINE_ID
    - make ci
    
sonarqube-check:
  stage: tests
  image:
    name: sonarsource/sonar-scanner-cli:latest
    entrypoint: [""]
  variables:
    SONAR_TOKEN: $SONAR_TOKEN
    GIT_STRATEGY: clone  
    GIT_DEPTH: "0"
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  artifacts:
    paths:
    - .sonar
  script:
    - sonar-scanner
       -X -Dsonar.qualitygate.wait=true
      -Dsonar.projectKey=EPM-${CI_PROJECT_NAME^^}
      -Dsonar.projectName=EPM-${CI_PROJECT_NAME^^}
      -Dsonar.host.url=$SONAR_URL
      -Dsonar.issuesReport.console.enable=true
      -Dsonar.gitlab.commit_sha=$CI_BUILD_REF
    - ls -lah
          
  allow_failure: true

.only-defaults:
  services:
    - name: docker:24.0.5-dind
      entrypoint: ["env", "-u", "DOCKER_HOST"]
      command: ["dockerd-entrypoint.sh"]
  image: docker:24.0.5
  tags:
    - kubernetes
  cache:
    key: "$CI_PIPELINE_ID"
    paths:
      - /tmp/coverage/
  before_script:
    - while ! nc -z localhost 2375 ; do sleep 1 ; done
    - docker --version
    - apk add --no-cache docker-compose make
    - echo $REGISTRY_PASSWORD  | docker login ${REGISTRY_URL} -u $REGISTRY_USERNAME --password-stdin
